version: 2.1



#################################

commands: 
  print_pipeline_id:
    steps:
     - run: echo ${CIRCLE_WORKFLOW_ID}





#################################
jobs:
  print_id: 
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: exit 1
      - run:
         name: Something went wrong
         command: echo "Hello Error!"
         when: on_fail

workflows:
  my_workflow:
    jobs:
      - print_id