version: 2.1



jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "echo saving Hello World output txt file"
          command: echo "text to output here" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths: 
            - output.txt
  
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps: 
      - attach_workspace:
          at: ~/
      - run:
        - name: "Print output txt"
        - command: cat ~/output.txt


workflows:
  test-env-vars:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output