version: 2.1



#################################

commands: 
  print_pipeline_id:
    steps:
     - run: echos ${CIRCLE_WORKFLOW_ID}





#################################
jobs:
  print_id: 
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
      - if_fails:
        - name: "Something went wrong"
        - run: echo "Hello Error!"
        - when: on_fail

workflows:
  my_workflow:
    jobs:
      - print_id